module.exports = [
  {
    name: "Sweet Pea",
    sex: "Female",
    color: "Brown",
    weight: "55 lbs",
    breed: "Labrador Retriever",
    age: 3,
    story: "Rescued from a local shelter",
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: false,
    status: "available",
  },
  {
    name: "Luna",
    sex: "Female",
    weight: "65 lbs",
    color: "Black",
    breed: "German Shepherd",
    age: 5,
    story: "Owner could no longer care for her",
    goodWithKids: true,
    goodWithDogs: false,
    goodWithCats: false,
    status: "available",
  },
  {
    name: "Max",
    weight: "60 lbs",
    sex: "Male",
    color: "Golden",
    breed: "Golden Retriever",
    age: 2,
    story: "Found as a stray",
    goodWithKids: true,
    goodWithDogs: true,
    goodWithCats: true,
    status: "pending",
  },
  {
    name: "Poppy",
    weight: "9 lbs",
    sex: "Female",
    color: "Tricolor",
    breed: "Dachshund",
    age: 1,
    story: "Rescued from a puppy mill",
    goodWithKids: false,
    goodWithDogs: true,
    goodWithCats: false,
    status: "available",
  },
];
